name: pangedza_delivery
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.4.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^0.13.5
  geocoding: ^2.1.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.4
  flutter_dotenv: ^5.1.0
  uuid: ^4.5.1
  supabase_flutter: ^1.10.0
  excel: ^2.0.4
  shared_preferences: ^2.2.2
  scrollable_positioned_list: ^0.3.8
  image_picker: ^1.0.4
  sign_in_with_apple: ^5.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/data/pangedza_menu_full_template (3).xlsx
    - assets/images/placeholder.jpg
