const supabaseUrl = 'https://ldncamguwbrpoouphewl.supabase.co';
const supabaseAnonKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkbmNhbWd1d2JycG9vdXBoZXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjI0MzksImV4cCI6MjA2NTk5ODQzOX0.tLQJugzPRJJhduarE2pbHS_ov1bnmklsWoyaiNS3Wk8';
